package org.prismlauncher.legacy;

import org.prismlauncher.utils.logging.Log;

import java.applet.Applet;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.JFrame;

import net.minecraft.Launcher;

final class LegacyFrame extends JFrame {
    private static final long serialVersionUID = 1L;

    private final Launcher launcher;

    public LegacyFrame(String title, Applet applet) {
        super(title);

        launcher = new Launcher(applet);

        applet.setStub(launcher);

        try {
            setIconImage(ImageIO.read(new File("icon.png")));
        } catch (IOException e) {
            Log.error("Failed to read window icon", e);
        }

        addWindowListener(new ForceExitHandler());
    }

    public void start(
            String user, String session, int width, int height, boolean maximize, String serverAddress, String serverPort, boolean demo) {
        // Implements support for launching in to multiplayer on classic servers using a
        // mpticket file generated by an external program and stored in the instance's
        // root folder.
        Path instanceFolder = Paths.get("..");
        Path mpticket = instanceFolder.resolve("mpticket");
        Path mpticketCorrupt = instanceFolder.resolve("mpticket.corrupt");

        if (Files.exists(mpticket)) {
            try {
                List<String> lines = Files.readAllLines(mpticket, StandardCharsets.UTF_8);

                if (lines.size() < 3) {
                    Files.move(mpticket, mpticketCorrupt, StandardCopyOption.REPLACE_EXISTING);

                    Log.warning("mpticket file is corrupted");
                } else {
                    // Assumes parameters are valid and in the correct order
                    launcher.setParameter("server", lines.get(0));
                    launcher.setParameter("port", lines.get(1));
                    launcher.setParameter("mppass", lines.get(2));
                }
            } catch (IOException e) {
                Log.error("Failed to read mpticket file", e);
            }
        }

        if (serverAddress != null) {
            launcher.setParameter("server", serverAddress);
            launcher.setParameter("port", serverPort);
        }

        launcher.setParameter("username", user);
        launcher.setParameter("sessionid", session);
        launcher.setParameter("stand-alone", true); // Show the quit button. This often doesn't seem to work.
        launcher.setParameter("haspaid", true); // Some old versions need this for world saves to work.
        launcher.setParameter("demo", demo);
        launcher.setParameter("fullscreen", false);

        add(launcher);

        launcher.setPreferredSize(new Dimension(width, height));

        pack();

        setLocationRelativeTo(null);
        setResizable(true);

        if (maximize)
            setExtendedState(MAXIMIZED_BOTH);

        validate();

        launcher.init();
        launcher.start();

        setVisible(true);
    }

    private final class ForceExitHandler extends WindowAdapter {
        @Override
        public void windowClosing(WindowEvent event) {
            // FIXME better solution

            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        Thread.sleep(30000L);
                    } catch (InterruptedException e) {
                        Log.error("Thread interrupted", e);
                    }

                    Log.warning("Forcing exit");
                    System.exit(0);
                }
            }).start();

            if (launcher != null) {
                launcher.stop();
                launcher.destroy();
            }

            // old minecraft versions can hang without this >_<
            System.exit(0);
        }
    }
}
